<?php

namespace app\controllers;

use app\models\form\ProductsnameForm;
use app\models\Productsname;
use yii\rest\ActiveController;
use Yii;

class ProductsnameController extends ActiveController
{
    public $modelClass = 'app\models\User';

    protected function verbs()
    {
        return ['list' => ['GET']]; // TODO: Change the autogenerated stub
    }
    public function actionAll() {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if (!Yii::$app->user->isGuest) {
            $countries = Productsname::find()->orderBy(['id' => SORT_DESC])->all();

            return $countries;
        } else {
            return ['admin' => false];
        }
    }

    public function actionUpdates() {
        if (!Yii::$app->user->isGuest) {
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            $result = new ProductsnameForm();
            $result->load(Yii::$app->request->bodyParams, '');
            if($result->update()) {
                return true;
            }

            return false;
        } else {
            return ['admin' => false];
        }
    }
    public function actionDeletes() {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if (!Yii::$app->user->isGuest) {
            $result = new ProductsnameForm();
            $result->load(Yii::$app->request->bodyParams, '');

            if($result->delete()) {
                return true;
            }

            return false;
        } else {
            return ['admin' => false];
        }
    }
    public function actionSaves() {
        if (!Yii::$app->user->isGuest) {
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            $result = new ProductsnameForm();
            $result->load(Yii::$app->request->bodyParams, '');

            if($result->send()) {
                return true;
            }

            return false;
        } else {
            return ['admin' => false];
        }
    }
}
